name = "runruby-worker"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-02-23"

[vars]
ALLOWED_HOSTS = "localhost,runruby.dev,*.runruby.dev,*.w-corp-staticblitz.com"
